---
driver:
  name: docker
  driver_config:
    use_sudo: false

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.2.1"

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
    - "recipe[chef-solo-search]"
    - "recipe[backup-test]"
    - "recipe[minitest-handler]"
    attributes: {}
